### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [L-u-k-e/IO-Stream#1]
you know that here: https://github.com/L-u-k-e/IO-Stream/blob/a3c6801272fd9439446ea98170fe7ebd86adf575/helpers/orm.js

if your intent for `equals(spec)` is to produce raw output, then you should set: `self._rawDBType = true`. And then you do need to use `^` when referencing the type, raw formatting will be applied automatically ;)

i.e.

``` js
var equals = function (spec) {
  var self = {};
  self._rawDBType = true;
  self.formatDBType = function () {
    var props = Object.keys(spec.items);
    var s = props.map(function (k) {
        return k + '=$(' + k + ')';
    });
    return pgp.as.format(s.join(' ' + spec.delimiter + ' '), spec.items);
  }
  return self;
};
```

Perhaps also for some other cases (custom types) that you have ;)

**Comment by L-u-k-e** [comment]
Hey Thanks!

I think I had it in there initially but took it out as a part of troubleshooting an issue that turned out to be un-related. 

These functions are far from finalized.
